namespace GestionAcademica.Forms
{
    partial class FormORM
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            tabControl = new TabControl();
            tabOrm = new TabPage();
            lblOrmTitulo = new Label();
            lblCodigoOrm = new Label();
            txtCodigoOrm = new TextBox();
            lblAlumnoOrm = new Label();
            txtAlumnoOrm = new TextBox();
            lblEstado = new Label();
            cboEstado = new ComboBox();
            btnNuevoOrm = new Button();
            btnGuardarOrm = new Button();
            btnActualizarOrm = new Button();
            btnEliminarOrm = new Button();
            dgvOrmEstudiantes = new DataGridView();
            tabReportes = new TabPage();
            lblReporteTitulo = new Label();
            lblTipoReporte = new Label();
            cboTipoReporte = new ComboBox();
            lblFiltro = new Label();
            txtFiltro = new TextBox();
            lblEstadoReporte = new Label();
            cboEstadoReporte = new ComboBox();
            lblDesde = new Label();
            dtpDesde = new DateTimePicker();
            lblHasta = new Label();
            dtpHasta = new DateTimePicker();
            lblNotaMinima = new Label();
            txtNotaMinima = new TextBox();
            btnGenerarReporte = new Button();
            btnLimpiarReporte = new Button();
            btnExportarReporte = new Button();
            lblResultado = new Label();
            dgvReporte = new DataGridView();
            btnCerrar = new Button();
            tabControl.SuspendLayout();
            tabOrm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvOrmEstudiantes).BeginInit();
            tabReportes.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvReporte).BeginInit();
            SuspendLayout();
            // tabControl
            tabControl.Controls.Add(tabOrm);
            tabControl.Controls.Add(tabReportes);
            tabControl.Location = new Point(20, 20);
            tabControl.Name = "tabControl";
            tabControl.SelectedIndex = 0;
            tabControl.Size = new Size(1120, 610);
            tabControl.TabIndex = 0;
            // tabOrm
            tabOrm.BackColor = Color.FromArgb(226, 232, 240);
            tabOrm.Controls.Add(lblOrmTitulo);
            tabOrm.Controls.Add(lblCodigoOrm);
            tabOrm.Controls.Add(txtCodigoOrm);
            tabOrm.Controls.Add(lblAlumnoOrm);
            tabOrm.Controls.Add(txtAlumnoOrm);
            tabOrm.Controls.Add(lblEstado);
            tabOrm.Controls.Add(cboEstado);
            tabOrm.Controls.Add(btnNuevoOrm);
            tabOrm.Controls.Add(btnGuardarOrm);
            tabOrm.Controls.Add(btnActualizarOrm);
            tabOrm.Controls.Add(btnEliminarOrm);
            tabOrm.Controls.Add(dgvOrmEstudiantes);
            tabOrm.Location = new Point(4, 29);
            tabOrm.Name = "tabOrm";
            tabOrm.Padding = new Padding(3);
            tabOrm.Size = new Size(1112, 577);
            tabOrm.TabIndex = 0;
            tabOrm.Text = "CRUD con Entity Framework Core";
            // lblOrmTitulo
            lblOrmTitulo.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblOrmTitulo.ForeColor = Color.FromArgb(27, 54, 93);
            lblOrmTitulo.Location = new Point(25, 18);
            lblOrmTitulo.Name = "lblOrmTitulo";
            lblOrmTitulo.Size = new Size(1050, 35);
            lblOrmTitulo.TabIndex = 0;
            lblOrmTitulo.Text = "CRUD de estudiantes mediante ORM (Entity Framework Core)";
            lblOrmTitulo.TextAlign = ContentAlignment.MiddleCenter;
            // labels/textboxes
            lblCodigoOrm.AutoSize = true;
            lblCodigoOrm.Location = new Point(35, 75);
            lblCodigoOrm.Name = "lblCodigoOrm";
            lblCodigoOrm.Text = "Código:";
            txtCodigoOrm.Location = new Point(115, 71);
            txtCodigoOrm.Name = "txtCodigoOrm";
            txtCodigoOrm.Size = new Size(180, 27);
            lblAlumnoOrm.AutoSize = true;
            lblAlumnoOrm.Location = new Point(320, 75);
            lblAlumnoOrm.Name = "lblAlumnoOrm";
            lblAlumnoOrm.Text = "Estudiante:";
            txtAlumnoOrm.Location = new Point(405, 71);
            txtAlumnoOrm.Name = "txtAlumnoOrm";
            txtAlumnoOrm.Size = new Size(280, 27);
            lblEstado.AutoSize = true;
            lblEstado.Location = new Point(710, 75);
            lblEstado.Name = "lblEstado";
            lblEstado.Text = "Estado:";
            cboEstado.DropDownStyle = ComboBoxStyle.DropDownList;
            cboEstado.Location = new Point(765, 71);
            cboEstado.Name = "cboEstado";
            cboEstado.Size = new Size(150, 28);
            // ORM buttons
            btnNuevoOrm.Location = new Point(35, 120);
            btnNuevoOrm.Name = "btnNuevoOrm";
            btnNuevoOrm.Size = new Size(120, 38);
            btnNuevoOrm.Text = "Nuevo";
            btnNuevoOrm.UseVisualStyleBackColor = true;
            btnNuevoOrm.Click += BtnNuevoOrm_Click;
            btnGuardarOrm.BackColor = Color.FromArgb(27, 54, 93);
            btnGuardarOrm.FlatStyle = FlatStyle.Flat;
            btnGuardarOrm.ForeColor = Color.White;
            btnGuardarOrm.Location = new Point(165, 120);
            btnGuardarOrm.Name = "btnGuardarOrm";
            btnGuardarOrm.Size = new Size(140, 38);
            btnGuardarOrm.Text = "Guardar ORM";
            btnGuardarOrm.UseVisualStyleBackColor = false;
            btnGuardarOrm.Click += BtnGuardarOrm_Click;
            btnActualizarOrm.Location = new Point(315, 120);
            btnActualizarOrm.Name = "btnActualizarOrm";
            btnActualizarOrm.Size = new Size(140, 38);
            btnActualizarOrm.Text = "Actualizar ORM";
            btnActualizarOrm.Click += BtnActualizarOrm_Click;
            btnEliminarOrm.Location = new Point(465, 120);
            btnEliminarOrm.Name = "btnEliminarOrm";
            btnEliminarOrm.Size = new Size(140, 38);
            btnEliminarOrm.Text = "Eliminar ORM";
            btnEliminarOrm.Click += BtnEliminarOrm_Click;
            // grid ORM
            dgvOrmEstudiantes.AllowUserToAddRows = false;
            dgvOrmEstudiantes.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvOrmEstudiantes.BackgroundColor = Color.White;
            dgvOrmEstudiantes.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvOrmEstudiantes.Location = new Point(35, 180);
            dgvOrmEstudiantes.MultiSelect = false;
            dgvOrmEstudiantes.Name = "dgvOrmEstudiantes";
            dgvOrmEstudiantes.ReadOnly = true;
            dgvOrmEstudiantes.RowHeadersVisible = false;
            dgvOrmEstudiantes.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvOrmEstudiantes.Size = new Size(1035, 350);
            dgvOrmEstudiantes.TabIndex = 11;
            dgvOrmEstudiantes.SelectionChanged += DgvOrmEstudiantes_SelectionChanged;
            // tabReportes
            tabReportes.BackColor = Color.FromArgb(226, 232, 240);
            tabReportes.Controls.Add(lblReporteTitulo);
            tabReportes.Controls.Add(lblTipoReporte);
            tabReportes.Controls.Add(cboTipoReporte);
            tabReportes.Controls.Add(lblFiltro);
            tabReportes.Controls.Add(txtFiltro);
            tabReportes.Controls.Add(lblEstadoReporte);
            tabReportes.Controls.Add(cboEstadoReporte);
            tabReportes.Controls.Add(lblDesde);
            tabReportes.Controls.Add(dtpDesde);
            tabReportes.Controls.Add(lblHasta);
            tabReportes.Controls.Add(dtpHasta);
            tabReportes.Controls.Add(lblNotaMinima);
            tabReportes.Controls.Add(txtNotaMinima);
            tabReportes.Controls.Add(btnGenerarReporte);
            tabReportes.Controls.Add(btnLimpiarReporte);
            tabReportes.Controls.Add(btnExportarReporte);
            tabReportes.Controls.Add(lblResultado);
            tabReportes.Controls.Add(dgvReporte);
            tabReportes.Location = new Point(4, 29);
            tabReportes.Name = "tabReportes";
            tabReportes.Padding = new Padding(3);
            tabReportes.Size = new Size(1112, 577);
            tabReportes.TabIndex = 1;
            tabReportes.Text = "Reportes dinámicos con LINQ";
            // report title
            lblReporteTitulo.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblReporteTitulo.ForeColor = Color.FromArgb(27, 54, 93);
            lblReporteTitulo.Location = new Point(25, 15);
            lblReporteTitulo.Name = "lblReporteTitulo";
            lblReporteTitulo.Size = new Size(1050, 35);
            lblReporteTitulo.TabIndex = 0;
            lblReporteTitulo.Text = "Reportes dinámicos integrados a la aplicación";
            lblReporteTitulo.TextAlign = ContentAlignment.MiddleCenter;
            // report filters
            lblTipoReporte.AutoSize = true;
            lblTipoReporte.Location = new Point(30, 68);
            lblTipoReporte.Text = "Tipo de reporte:";
            cboTipoReporte.DropDownStyle = ComboBoxStyle.DropDownList;
            cboTipoReporte.Location = new Point(165, 64);
            cboTipoReporte.Name = "cboTipoReporte";
            cboTipoReporte.Size = new Size(270, 28);
            cboTipoReporte.SelectedIndexChanged += CboTipoReporte_SelectedIndexChanged;
            lblFiltro.AutoSize = true;
            lblFiltro.Location = new Point(455, 68);
            lblFiltro.Name = "lblFiltro";
            lblFiltro.Text = "Código o estudiante:";
            txtFiltro.Location = new Point(725, 64);
            txtFiltro.Name = "txtFiltro";
            txtFiltro.Size = new Size(220, 27);
            lblEstadoReporte.AutoSize = true;
            lblEstadoReporte.Location = new Point(30, 108);
            lblEstadoReporte.Name = "lblEstadoReporte";
            lblEstadoReporte.Text = "Estado:";
            cboEstadoReporte.DropDownStyle = ComboBoxStyle.DropDownList;
            cboEstadoReporte.Location = new Point(165, 104);
            cboEstadoReporte.Name = "cboEstadoReporte";
            cboEstadoReporte.Size = new Size(200, 28);
            lblDesde.AutoSize = true;
            lblDesde.Location = new Point(30, 108);
            lblDesde.Name = "lblDesde";
            lblDesde.Text = "Desde:";
            dtpDesde.Format = DateTimePickerFormat.Short;
            dtpDesde.Location = new Point(165, 104);
            dtpDesde.Name = "dtpDesde";
            dtpDesde.Size = new Size(150, 27);
            dtpDesde.Value = DateTime.Today.AddMonths(-1);
            lblHasta.AutoSize = true;
            lblHasta.Location = new Point(340, 108);
            lblHasta.Name = "lblHasta";
            lblHasta.Text = "Hasta:";
            dtpHasta.Format = DateTimePickerFormat.Short;
            dtpHasta.Location = new Point(410, 104);
            dtpHasta.Name = "dtpHasta";
            dtpHasta.Size = new Size(150, 27);
            dtpHasta.Value = DateTime.Today;
            lblNotaMinima.AutoSize = true;
            lblNotaMinima.Location = new Point(30, 108);
            lblNotaMinima.Name = "lblNotaMinima";
            lblNotaMinima.Text = "Nota mínima:";
            txtNotaMinima.Location = new Point(165, 104);
            txtNotaMinima.Name = "txtNotaMinima";
            txtNotaMinima.Size = new Size(100, 27);
            // report buttons
            btnGenerarReporte.BackColor = Color.FromArgb(27, 54, 93);
            btnGenerarReporte.FlatStyle = FlatStyle.Flat;
            btnGenerarReporte.ForeColor = Color.White;
            btnGenerarReporte.Location = new Point(30, 150);
            btnGenerarReporte.Name = "btnGenerarReporte";
            btnGenerarReporte.Size = new Size(150, 38);
            btnGenerarReporte.Text = "Generar reporte";
            btnGenerarReporte.UseVisualStyleBackColor = false;
            btnGenerarReporte.Click += BtnGenerarReporte_Click;
            btnLimpiarReporte.Location = new Point(195, 150);
            btnLimpiarReporte.Name = "btnLimpiarReporte";
            btnLimpiarReporte.Size = new Size(120, 38);
            btnLimpiarReporte.Text = "Limpiar";
            btnLimpiarReporte.Click += BtnLimpiarReporte_Click;
            btnExportarReporte.Location = new Point(330, 150);
            btnExportarReporte.Name = "btnExportarReporte";
            btnExportarReporte.Size = new Size(135, 38);
            btnExportarReporte.Text = "Exportar CSV";
            btnExportarReporte.Click += BtnExportarReporte_Click;
            lblResultado.AutoSize = true;
            lblResultado.Location = new Point(30, 200);
            lblResultado.Name = "lblResultado";
            lblResultado.Text = "Registros encontrados: 0";
            // report grid
            dgvReporte.AllowUserToAddRows = false;
            dgvReporte.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvReporte.BackgroundColor = Color.White;
            dgvReporte.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvReporte.Location = new Point(30, 230);
            dgvReporte.MultiSelect = false;
            dgvReporte.Name = "dgvReporte";
            dgvReporte.ReadOnly = true;
            dgvReporte.RowHeadersVisible = false;
            dgvReporte.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvReporte.Size = new Size(1040, 300);
            dgvReporte.TabIndex = 20;
            // close
            btnCerrar.Location = new Point(990, 645);
            btnCerrar.Name = "btnCerrar";
            btnCerrar.Size = new Size(150, 38);
            btnCerrar.TabIndex = 2;
            btnCerrar.Text = "Cerrar";
            btnCerrar.UseVisualStyleBackColor = true;
            btnCerrar.Click += BtnCerrar_Click;
            // form
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(226, 232, 240);
            ClientSize = new Size(1160, 700);
            Controls.Add(btnCerrar);
            Controls.Add(tabControl);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "FormEntregable6";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Entregable 6 - ORM y Reportes";
            tabControl.ResumeLayout(false);
            tabOrm.ResumeLayout(false);
            tabOrm.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvOrmEstudiantes).EndInit();
            tabReportes.ResumeLayout(false);
            tabReportes.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvReporte).EndInit();
            ResumeLayout(false);
        }

        private TabControl tabControl;
        private TabPage tabOrm;
        private Label lblOrmTitulo;
        private Label lblCodigoOrm;
        private TextBox txtCodigoOrm;
        private Label lblAlumnoOrm;
        private TextBox txtAlumnoOrm;
        private Label lblEstado;
        private ComboBox cboEstado;
        private Button btnNuevoOrm;
        private Button btnGuardarOrm;
        private Button btnActualizarOrm;
        private Button btnEliminarOrm;
        private DataGridView dgvOrmEstudiantes;
        private TabPage tabReportes;
        private Label lblReporteTitulo;
        private Label lblTipoReporte;
        private ComboBox cboTipoReporte;
        private Label lblFiltro;
        private TextBox txtFiltro;
        private Label lblEstadoReporte;
        private ComboBox cboEstadoReporte;
        private Label lblDesde;
        private DateTimePicker dtpDesde;
        private Label lblHasta;
        private DateTimePicker dtpHasta;
        private Label lblNotaMinima;
        private TextBox txtNotaMinima;
        private Button btnGenerarReporte;
        private Button btnLimpiarReporte;
        private Button btnExportarReporte;
        private Label lblResultado;
        private DataGridView dgvReporte;
        private Button btnCerrar;
    }
}
